// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: aria2.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Aria2Service_AddUri_FullMethodName                  = "/aria2go.api.Aria2Service/AddUri"
	Aria2Service_AddTorrent_FullMethodName              = "/aria2go.api.Aria2Service/AddTorrent"
	Aria2Service_AddMetalink_FullMethodName             = "/aria2go.api.Aria2Service/AddMetalink"
	Aria2Service_Remove_FullMethodName                  = "/aria2go.api.Aria2Service/Remove"
	Aria2Service_ForceRemove_FullMethodName             = "/aria2go.api.Aria2Service/ForceRemove"
	Aria2Service_Pause_FullMethodName                   = "/aria2go.api.Aria2Service/Pause"
	Aria2Service_PauseAll_FullMethodName                = "/aria2go.api.Aria2Service/PauseAll"
	Aria2Service_ForcePause_FullMethodName              = "/aria2go.api.Aria2Service/ForcePause"
	Aria2Service_ForcePauseAll_FullMethodName           = "/aria2go.api.Aria2Service/ForcePauseAll"
	Aria2Service_Unpause_FullMethodName                 = "/aria2go.api.Aria2Service/Unpause"
	Aria2Service_UnpauseAll_FullMethodName              = "/aria2go.api.Aria2Service/UnpauseAll"
	Aria2Service_TellStatus_FullMethodName              = "/aria2go.api.Aria2Service/TellStatus"
	Aria2Service_TellActive_FullMethodName              = "/aria2go.api.Aria2Service/TellActive"
	Aria2Service_TellWaiting_FullMethodName             = "/aria2go.api.Aria2Service/TellWaiting"
	Aria2Service_TellStopped_FullMethodName             = "/aria2go.api.Aria2Service/TellStopped"
	Aria2Service_GetUris_FullMethodName                 = "/aria2go.api.Aria2Service/GetUris"
	Aria2Service_GetFiles_FullMethodName                = "/aria2go.api.Aria2Service/GetFiles"
	Aria2Service_GetPeers_FullMethodName                = "/aria2go.api.Aria2Service/GetPeers"
	Aria2Service_GetServers_FullMethodName              = "/aria2go.api.Aria2Service/GetServers"
	Aria2Service_GetGlobalStat_FullMethodName           = "/aria2go.api.Aria2Service/GetGlobalStat"
	Aria2Service_GetOption_FullMethodName               = "/aria2go.api.Aria2Service/GetOption"
	Aria2Service_ChangeOption_FullMethodName            = "/aria2go.api.Aria2Service/ChangeOption"
	Aria2Service_GetGlobalOption_FullMethodName         = "/aria2go.api.Aria2Service/GetGlobalOption"
	Aria2Service_ChangeGlobalOption_FullMethodName      = "/aria2go.api.Aria2Service/ChangeGlobalOption"
	Aria2Service_Shutdown_FullMethodName                = "/aria2go.api.Aria2Service/Shutdown"
	Aria2Service_ForceShutdown_FullMethodName           = "/aria2go.api.Aria2Service/ForceShutdown"
	Aria2Service_SaveSession_FullMethodName             = "/aria2go.api.Aria2Service/SaveSession"
	Aria2Service_SystemMulticall_FullMethodName         = "/aria2go.api.Aria2Service/SystemMulticall"
	Aria2Service_SystemListMethods_FullMethodName       = "/aria2go.api.Aria2Service/SystemListMethods"
	Aria2Service_SystemListNotifications_FullMethodName = "/aria2go.api.Aria2Service/SystemListNotifications"
)

// Aria2ServiceClient is the client API for Aria2Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Aria2服务定义，提供完整的下载管理功能
type Aria2ServiceClient interface {
	// 下载管理
	AddUri(ctx context.Context, in *AddUriRequest, opts ...grpc.CallOption) (*AddUriResponse, error)
	AddTorrent(ctx context.Context, in *AddTorrentRequest, opts ...grpc.CallOption) (*AddTorrentResponse, error)
	AddMetalink(ctx context.Context, in *AddMetalinkRequest, opts ...grpc.CallOption) (*AddMetalinkResponse, error)
	Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveResponse, error)
	ForceRemove(ctx context.Context, in *ForceRemoveRequest, opts ...grpc.CallOption) (*ForceRemoveResponse, error)
	Pause(ctx context.Context, in *PauseRequest, opts ...grpc.CallOption) (*PauseResponse, error)
	PauseAll(ctx context.Context, in *PauseAllRequest, opts ...grpc.CallOption) (*PauseAllResponse, error)
	ForcePause(ctx context.Context, in *ForcePauseRequest, opts ...grpc.CallOption) (*ForcePauseResponse, error)
	ForcePauseAll(ctx context.Context, in *ForcePauseAllRequest, opts ...grpc.CallOption) (*ForcePauseAllResponse, error)
	Unpause(ctx context.Context, in *UnpauseRequest, opts ...grpc.CallOption) (*UnpauseResponse, error)
	UnpauseAll(ctx context.Context, in *UnpauseAllRequest, opts ...grpc.CallOption) (*UnpauseAllResponse, error)
	// 状态查询
	TellStatus(ctx context.Context, in *TellStatusRequest, opts ...grpc.CallOption) (*TellStatusResponse, error)
	TellActive(ctx context.Context, in *TellActiveRequest, opts ...grpc.CallOption) (*TellActiveResponse, error)
	TellWaiting(ctx context.Context, in *TellWaitingRequest, opts ...grpc.CallOption) (*TellWaitingResponse, error)
	TellStopped(ctx context.Context, in *TellStoppedRequest, opts ...grpc.CallOption) (*TellStoppedResponse, error)
	// 信息获取
	GetUris(ctx context.Context, in *GetUrisRequest, opts ...grpc.CallOption) (*GetUrisResponse, error)
	GetFiles(ctx context.Context, in *GetFilesRequest, opts ...grpc.CallOption) (*GetFilesResponse, error)
	GetPeers(ctx context.Context, in *GetPeersRequest, opts ...grpc.CallOption) (*GetPeersResponse, error)
	GetServers(ctx context.Context, in *GetServersRequest, opts ...grpc.CallOption) (*GetServersResponse, error)
	GetGlobalStat(ctx context.Context, in *GetGlobalStatRequest, opts ...grpc.CallOption) (*GetGlobalStatResponse, error)
	// 配置管理
	GetOption(ctx context.Context, in *GetOptionRequest, opts ...grpc.CallOption) (*GetOptionResponse, error)
	ChangeOption(ctx context.Context, in *ChangeOptionRequest, opts ...grpc.CallOption) (*ChangeOptionResponse, error)
	GetGlobalOption(ctx context.Context, in *GetGlobalOptionRequest, opts ...grpc.CallOption) (*GetGlobalOptionResponse, error)
	ChangeGlobalOption(ctx context.Context, in *ChangeGlobalOptionRequest, opts ...grpc.CallOption) (*ChangeGlobalOptionResponse, error)
	// 系统操作
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error)
	ForceShutdown(ctx context.Context, in *ForceShutdownRequest, opts ...grpc.CallOption) (*ForceShutdownResponse, error)
	SaveSession(ctx context.Context, in *SaveSessionRequest, opts ...grpc.CallOption) (*SaveSessionResponse, error)
	// 系统方法
	SystemMulticall(ctx context.Context, in *SystemMulticallRequest, opts ...grpc.CallOption) (*SystemMulticallResponse, error)
	SystemListMethods(ctx context.Context, in *SystemListMethodsRequest, opts ...grpc.CallOption) (*SystemListMethodsResponse, error)
	SystemListNotifications(ctx context.Context, in *SystemListNotificationsRequest, opts ...grpc.CallOption) (*SystemListNotificationsResponse, error)
}

type aria2ServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAria2ServiceClient(cc grpc.ClientConnInterface) Aria2ServiceClient {
	return &aria2ServiceClient{cc}
}

func (c *aria2ServiceClient) AddUri(ctx context.Context, in *AddUriRequest, opts ...grpc.CallOption) (*AddUriResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddUriResponse)
	err := c.cc.Invoke(ctx, Aria2Service_AddUri_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aria2ServiceClient) AddTorrent(ctx context.Context, in *AddTorrentRequest, opts ...grpc.CallOption) (*AddTorrentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddTorrentResponse)
	err := c.cc.Invoke(ctx, Aria2Service_AddTorrent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aria2ServiceClient) AddMetalink(ctx context.Context, in *AddMetalinkRequest, opts ...grpc.CallOption) (*AddMetalinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddMetalinkResponse)
	err := c.cc.Invoke(ctx, Aria2Service_AddMetalink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aria2ServiceClient) Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveResponse)
	err := c.cc.Invoke(ctx, Aria2Service_Remove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aria2ServiceClient) ForceRemove(ctx context.Context, in *ForceRemoveRequest, opts ...grpc.CallOption) (*ForceRemoveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForceRemoveResponse)
	err := c.cc.Invoke(ctx, Aria2Service_ForceRemove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aria2ServiceClient) Pause(ctx context.Context, in *PauseRequest, opts ...grpc.CallOption) (*PauseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PauseResponse)
	err := c.cc.Invoke(ctx, Aria2Service_Pause_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aria2ServiceClient) PauseAll(ctx context.Context, in *PauseAllRequest, opts ...grpc.CallOption) (*PauseAllResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PauseAllResponse)
	err := c.cc.Invoke(ctx, Aria2Service_PauseAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aria2ServiceClient) ForcePause(ctx context.Context, in *ForcePauseRequest, opts ...grpc.CallOption) (*ForcePauseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForcePauseResponse)
	err := c.cc.Invoke(ctx, Aria2Service_ForcePause_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aria2ServiceClient) ForcePauseAll(ctx context.Context, in *ForcePauseAllRequest, opts ...grpc.CallOption) (*ForcePauseAllResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForcePauseAllResponse)
	err := c.cc.Invoke(ctx, Aria2Service_ForcePauseAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aria2ServiceClient) Unpause(ctx context.Context, in *UnpauseRequest, opts ...grpc.CallOption) (*UnpauseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnpauseResponse)
	err := c.cc.Invoke(ctx, Aria2Service_Unpause_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aria2ServiceClient) UnpauseAll(ctx context.Context, in *UnpauseAllRequest, opts ...grpc.CallOption) (*UnpauseAllResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnpauseAllResponse)
	err := c.cc.Invoke(ctx, Aria2Service_UnpauseAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aria2ServiceClient) TellStatus(ctx context.Context, in *TellStatusRequest, opts ...grpc.CallOption) (*TellStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TellStatusResponse)
	err := c.cc.Invoke(ctx, Aria2Service_TellStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aria2ServiceClient) TellActive(ctx context.Context, in *TellActiveRequest, opts ...grpc.CallOption) (*TellActiveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TellActiveResponse)
	err := c.cc.Invoke(ctx, Aria2Service_TellActive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aria2ServiceClient) TellWaiting(ctx context.Context, in *TellWaitingRequest, opts ...grpc.CallOption) (*TellWaitingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TellWaitingResponse)
	err := c.cc.Invoke(ctx, Aria2Service_TellWaiting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aria2ServiceClient) TellStopped(ctx context.Context, in *TellStoppedRequest, opts ...grpc.CallOption) (*TellStoppedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TellStoppedResponse)
	err := c.cc.Invoke(ctx, Aria2Service_TellStopped_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aria2ServiceClient) GetUris(ctx context.Context, in *GetUrisRequest, opts ...grpc.CallOption) (*GetUrisResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUrisResponse)
	err := c.cc.Invoke(ctx, Aria2Service_GetUris_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aria2ServiceClient) GetFiles(ctx context.Context, in *GetFilesRequest, opts ...grpc.CallOption) (*GetFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFilesResponse)
	err := c.cc.Invoke(ctx, Aria2Service_GetFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aria2ServiceClient) GetPeers(ctx context.Context, in *GetPeersRequest, opts ...grpc.CallOption) (*GetPeersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPeersResponse)
	err := c.cc.Invoke(ctx, Aria2Service_GetPeers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aria2ServiceClient) GetServers(ctx context.Context, in *GetServersRequest, opts ...grpc.CallOption) (*GetServersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetServersResponse)
	err := c.cc.Invoke(ctx, Aria2Service_GetServers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aria2ServiceClient) GetGlobalStat(ctx context.Context, in *GetGlobalStatRequest, opts ...grpc.CallOption) (*GetGlobalStatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGlobalStatResponse)
	err := c.cc.Invoke(ctx, Aria2Service_GetGlobalStat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aria2ServiceClient) GetOption(ctx context.Context, in *GetOptionRequest, opts ...grpc.CallOption) (*GetOptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOptionResponse)
	err := c.cc.Invoke(ctx, Aria2Service_GetOption_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aria2ServiceClient) ChangeOption(ctx context.Context, in *ChangeOptionRequest, opts ...grpc.CallOption) (*ChangeOptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChangeOptionResponse)
	err := c.cc.Invoke(ctx, Aria2Service_ChangeOption_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aria2ServiceClient) GetGlobalOption(ctx context.Context, in *GetGlobalOptionRequest, opts ...grpc.CallOption) (*GetGlobalOptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGlobalOptionResponse)
	err := c.cc.Invoke(ctx, Aria2Service_GetGlobalOption_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aria2ServiceClient) ChangeGlobalOption(ctx context.Context, in *ChangeGlobalOptionRequest, opts ...grpc.CallOption) (*ChangeGlobalOptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChangeGlobalOptionResponse)
	err := c.cc.Invoke(ctx, Aria2Service_ChangeGlobalOption_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aria2ServiceClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShutdownResponse)
	err := c.cc.Invoke(ctx, Aria2Service_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aria2ServiceClient) ForceShutdown(ctx context.Context, in *ForceShutdownRequest, opts ...grpc.CallOption) (*ForceShutdownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForceShutdownResponse)
	err := c.cc.Invoke(ctx, Aria2Service_ForceShutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aria2ServiceClient) SaveSession(ctx context.Context, in *SaveSessionRequest, opts ...grpc.CallOption) (*SaveSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveSessionResponse)
	err := c.cc.Invoke(ctx, Aria2Service_SaveSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aria2ServiceClient) SystemMulticall(ctx context.Context, in *SystemMulticallRequest, opts ...grpc.CallOption) (*SystemMulticallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SystemMulticallResponse)
	err := c.cc.Invoke(ctx, Aria2Service_SystemMulticall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aria2ServiceClient) SystemListMethods(ctx context.Context, in *SystemListMethodsRequest, opts ...grpc.CallOption) (*SystemListMethodsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SystemListMethodsResponse)
	err := c.cc.Invoke(ctx, Aria2Service_SystemListMethods_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aria2ServiceClient) SystemListNotifications(ctx context.Context, in *SystemListNotificationsRequest, opts ...grpc.CallOption) (*SystemListNotificationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SystemListNotificationsResponse)
	err := c.cc.Invoke(ctx, Aria2Service_SystemListNotifications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Aria2ServiceServer is the server API for Aria2Service service.
// All implementations must embed UnimplementedAria2ServiceServer
// for forward compatibility.
//
// Aria2服务定义，提供完整的下载管理功能
type Aria2ServiceServer interface {
	// 下载管理
	AddUri(context.Context, *AddUriRequest) (*AddUriResponse, error)
	AddTorrent(context.Context, *AddTorrentRequest) (*AddTorrentResponse, error)
	AddMetalink(context.Context, *AddMetalinkRequest) (*AddMetalinkResponse, error)
	Remove(context.Context, *RemoveRequest) (*RemoveResponse, error)
	ForceRemove(context.Context, *ForceRemoveRequest) (*ForceRemoveResponse, error)
	Pause(context.Context, *PauseRequest) (*PauseResponse, error)
	PauseAll(context.Context, *PauseAllRequest) (*PauseAllResponse, error)
	ForcePause(context.Context, *ForcePauseRequest) (*ForcePauseResponse, error)
	ForcePauseAll(context.Context, *ForcePauseAllRequest) (*ForcePauseAllResponse, error)
	Unpause(context.Context, *UnpauseRequest) (*UnpauseResponse, error)
	UnpauseAll(context.Context, *UnpauseAllRequest) (*UnpauseAllResponse, error)
	// 状态查询
	TellStatus(context.Context, *TellStatusRequest) (*TellStatusResponse, error)
	TellActive(context.Context, *TellActiveRequest) (*TellActiveResponse, error)
	TellWaiting(context.Context, *TellWaitingRequest) (*TellWaitingResponse, error)
	TellStopped(context.Context, *TellStoppedRequest) (*TellStoppedResponse, error)
	// 信息获取
	GetUris(context.Context, *GetUrisRequest) (*GetUrisResponse, error)
	GetFiles(context.Context, *GetFilesRequest) (*GetFilesResponse, error)
	GetPeers(context.Context, *GetPeersRequest) (*GetPeersResponse, error)
	GetServers(context.Context, *GetServersRequest) (*GetServersResponse, error)
	GetGlobalStat(context.Context, *GetGlobalStatRequest) (*GetGlobalStatResponse, error)
	// 配置管理
	GetOption(context.Context, *GetOptionRequest) (*GetOptionResponse, error)
	ChangeOption(context.Context, *ChangeOptionRequest) (*ChangeOptionResponse, error)
	GetGlobalOption(context.Context, *GetGlobalOptionRequest) (*GetGlobalOptionResponse, error)
	ChangeGlobalOption(context.Context, *ChangeGlobalOptionRequest) (*ChangeGlobalOptionResponse, error)
	// 系统操作
	Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error)
	ForceShutdown(context.Context, *ForceShutdownRequest) (*ForceShutdownResponse, error)
	SaveSession(context.Context, *SaveSessionRequest) (*SaveSessionResponse, error)
	// 系统方法
	SystemMulticall(context.Context, *SystemMulticallRequest) (*SystemMulticallResponse, error)
	SystemListMethods(context.Context, *SystemListMethodsRequest) (*SystemListMethodsResponse, error)
	SystemListNotifications(context.Context, *SystemListNotificationsRequest) (*SystemListNotificationsResponse, error)
	mustEmbedUnimplementedAria2ServiceServer()
}

// UnimplementedAria2ServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAria2ServiceServer struct{}

func (UnimplementedAria2ServiceServer) AddUri(context.Context, *AddUriRequest) (*AddUriResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddUri not implemented")
}
func (UnimplementedAria2ServiceServer) AddTorrent(context.Context, *AddTorrentRequest) (*AddTorrentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddTorrent not implemented")
}
func (UnimplementedAria2ServiceServer) AddMetalink(context.Context, *AddMetalinkRequest) (*AddMetalinkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddMetalink not implemented")
}
func (UnimplementedAria2ServiceServer) Remove(context.Context, *RemoveRequest) (*RemoveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Remove not implemented")
}
func (UnimplementedAria2ServiceServer) ForceRemove(context.Context, *ForceRemoveRequest) (*ForceRemoveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ForceRemove not implemented")
}
func (UnimplementedAria2ServiceServer) Pause(context.Context, *PauseRequest) (*PauseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Pause not implemented")
}
func (UnimplementedAria2ServiceServer) PauseAll(context.Context, *PauseAllRequest) (*PauseAllResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PauseAll not implemented")
}
func (UnimplementedAria2ServiceServer) ForcePause(context.Context, *ForcePauseRequest) (*ForcePauseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ForcePause not implemented")
}
func (UnimplementedAria2ServiceServer) ForcePauseAll(context.Context, *ForcePauseAllRequest) (*ForcePauseAllResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ForcePauseAll not implemented")
}
func (UnimplementedAria2ServiceServer) Unpause(context.Context, *UnpauseRequest) (*UnpauseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Unpause not implemented")
}
func (UnimplementedAria2ServiceServer) UnpauseAll(context.Context, *UnpauseAllRequest) (*UnpauseAllResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnpauseAll not implemented")
}
func (UnimplementedAria2ServiceServer) TellStatus(context.Context, *TellStatusRequest) (*TellStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TellStatus not implemented")
}
func (UnimplementedAria2ServiceServer) TellActive(context.Context, *TellActiveRequest) (*TellActiveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TellActive not implemented")
}
func (UnimplementedAria2ServiceServer) TellWaiting(context.Context, *TellWaitingRequest) (*TellWaitingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TellWaiting not implemented")
}
func (UnimplementedAria2ServiceServer) TellStopped(context.Context, *TellStoppedRequest) (*TellStoppedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TellStopped not implemented")
}
func (UnimplementedAria2ServiceServer) GetUris(context.Context, *GetUrisRequest) (*GetUrisResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUris not implemented")
}
func (UnimplementedAria2ServiceServer) GetFiles(context.Context, *GetFilesRequest) (*GetFilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFiles not implemented")
}
func (UnimplementedAria2ServiceServer) GetPeers(context.Context, *GetPeersRequest) (*GetPeersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPeers not implemented")
}
func (UnimplementedAria2ServiceServer) GetServers(context.Context, *GetServersRequest) (*GetServersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetServers not implemented")
}
func (UnimplementedAria2ServiceServer) GetGlobalStat(context.Context, *GetGlobalStatRequest) (*GetGlobalStatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGlobalStat not implemented")
}
func (UnimplementedAria2ServiceServer) GetOption(context.Context, *GetOptionRequest) (*GetOptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOption not implemented")
}
func (UnimplementedAria2ServiceServer) ChangeOption(context.Context, *ChangeOptionRequest) (*ChangeOptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangeOption not implemented")
}
func (UnimplementedAria2ServiceServer) GetGlobalOption(context.Context, *GetGlobalOptionRequest) (*GetGlobalOptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGlobalOption not implemented")
}
func (UnimplementedAria2ServiceServer) ChangeGlobalOption(context.Context, *ChangeGlobalOptionRequest) (*ChangeGlobalOptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangeGlobalOption not implemented")
}
func (UnimplementedAria2ServiceServer) Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedAria2ServiceServer) ForceShutdown(context.Context, *ForceShutdownRequest) (*ForceShutdownResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ForceShutdown not implemented")
}
func (UnimplementedAria2ServiceServer) SaveSession(context.Context, *SaveSessionRequest) (*SaveSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveSession not implemented")
}
func (UnimplementedAria2ServiceServer) SystemMulticall(context.Context, *SystemMulticallRequest) (*SystemMulticallResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SystemMulticall not implemented")
}
func (UnimplementedAria2ServiceServer) SystemListMethods(context.Context, *SystemListMethodsRequest) (*SystemListMethodsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SystemListMethods not implemented")
}
func (UnimplementedAria2ServiceServer) SystemListNotifications(context.Context, *SystemListNotificationsRequest) (*SystemListNotificationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SystemListNotifications not implemented")
}
func (UnimplementedAria2ServiceServer) mustEmbedUnimplementedAria2ServiceServer() {}
func (UnimplementedAria2ServiceServer) testEmbeddedByValue()                      {}

// UnsafeAria2ServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Aria2ServiceServer will
// result in compilation errors.
type UnsafeAria2ServiceServer interface {
	mustEmbedUnimplementedAria2ServiceServer()
}

func RegisterAria2ServiceServer(s grpc.ServiceRegistrar, srv Aria2ServiceServer) {
	// If the following call panics, it indicates UnimplementedAria2ServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Aria2Service_ServiceDesc, srv)
}

func _Aria2Service_AddUri_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUriRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Aria2ServiceServer).AddUri(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Aria2Service_AddUri_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Aria2ServiceServer).AddUri(ctx, req.(*AddUriRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Aria2Service_AddTorrent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTorrentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Aria2ServiceServer).AddTorrent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Aria2Service_AddTorrent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Aria2ServiceServer).AddTorrent(ctx, req.(*AddTorrentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Aria2Service_AddMetalink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMetalinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Aria2ServiceServer).AddMetalink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Aria2Service_AddMetalink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Aria2ServiceServer).AddMetalink(ctx, req.(*AddMetalinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Aria2Service_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Aria2ServiceServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Aria2Service_Remove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Aria2ServiceServer).Remove(ctx, req.(*RemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Aria2Service_ForceRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForceRemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Aria2ServiceServer).ForceRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Aria2Service_ForceRemove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Aria2ServiceServer).ForceRemove(ctx, req.(*ForceRemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Aria2Service_Pause_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Aria2ServiceServer).Pause(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Aria2Service_Pause_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Aria2ServiceServer).Pause(ctx, req.(*PauseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Aria2Service_PauseAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Aria2ServiceServer).PauseAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Aria2Service_PauseAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Aria2ServiceServer).PauseAll(ctx, req.(*PauseAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Aria2Service_ForcePause_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForcePauseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Aria2ServiceServer).ForcePause(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Aria2Service_ForcePause_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Aria2ServiceServer).ForcePause(ctx, req.(*ForcePauseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Aria2Service_ForcePauseAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForcePauseAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Aria2ServiceServer).ForcePauseAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Aria2Service_ForcePauseAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Aria2ServiceServer).ForcePauseAll(ctx, req.(*ForcePauseAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Aria2Service_Unpause_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnpauseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Aria2ServiceServer).Unpause(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Aria2Service_Unpause_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Aria2ServiceServer).Unpause(ctx, req.(*UnpauseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Aria2Service_UnpauseAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnpauseAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Aria2ServiceServer).UnpauseAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Aria2Service_UnpauseAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Aria2ServiceServer).UnpauseAll(ctx, req.(*UnpauseAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Aria2Service_TellStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TellStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Aria2ServiceServer).TellStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Aria2Service_TellStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Aria2ServiceServer).TellStatus(ctx, req.(*TellStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Aria2Service_TellActive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TellActiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Aria2ServiceServer).TellActive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Aria2Service_TellActive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Aria2ServiceServer).TellActive(ctx, req.(*TellActiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Aria2Service_TellWaiting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TellWaitingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Aria2ServiceServer).TellWaiting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Aria2Service_TellWaiting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Aria2ServiceServer).TellWaiting(ctx, req.(*TellWaitingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Aria2Service_TellStopped_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TellStoppedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Aria2ServiceServer).TellStopped(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Aria2Service_TellStopped_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Aria2ServiceServer).TellStopped(ctx, req.(*TellStoppedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Aria2Service_GetUris_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUrisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Aria2ServiceServer).GetUris(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Aria2Service_GetUris_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Aria2ServiceServer).GetUris(ctx, req.(*GetUrisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Aria2Service_GetFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Aria2ServiceServer).GetFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Aria2Service_GetFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Aria2ServiceServer).GetFiles(ctx, req.(*GetFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Aria2Service_GetPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPeersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Aria2ServiceServer).GetPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Aria2Service_GetPeers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Aria2ServiceServer).GetPeers(ctx, req.(*GetPeersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Aria2Service_GetServers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Aria2ServiceServer).GetServers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Aria2Service_GetServers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Aria2ServiceServer).GetServers(ctx, req.(*GetServersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Aria2Service_GetGlobalStat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGlobalStatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Aria2ServiceServer).GetGlobalStat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Aria2Service_GetGlobalStat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Aria2ServiceServer).GetGlobalStat(ctx, req.(*GetGlobalStatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Aria2Service_GetOption_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Aria2ServiceServer).GetOption(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Aria2Service_GetOption_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Aria2ServiceServer).GetOption(ctx, req.(*GetOptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Aria2Service_ChangeOption_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeOptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Aria2ServiceServer).ChangeOption(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Aria2Service_ChangeOption_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Aria2ServiceServer).ChangeOption(ctx, req.(*ChangeOptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Aria2Service_GetGlobalOption_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGlobalOptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Aria2ServiceServer).GetGlobalOption(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Aria2Service_GetGlobalOption_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Aria2ServiceServer).GetGlobalOption(ctx, req.(*GetGlobalOptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Aria2Service_ChangeGlobalOption_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeGlobalOptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Aria2ServiceServer).ChangeGlobalOption(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Aria2Service_ChangeGlobalOption_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Aria2ServiceServer).ChangeGlobalOption(ctx, req.(*ChangeGlobalOptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Aria2Service_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Aria2ServiceServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Aria2Service_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Aria2ServiceServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Aria2Service_ForceShutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForceShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Aria2ServiceServer).ForceShutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Aria2Service_ForceShutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Aria2ServiceServer).ForceShutdown(ctx, req.(*ForceShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Aria2Service_SaveSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Aria2ServiceServer).SaveSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Aria2Service_SaveSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Aria2ServiceServer).SaveSession(ctx, req.(*SaveSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Aria2Service_SystemMulticall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SystemMulticallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Aria2ServiceServer).SystemMulticall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Aria2Service_SystemMulticall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Aria2ServiceServer).SystemMulticall(ctx, req.(*SystemMulticallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Aria2Service_SystemListMethods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SystemListMethodsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Aria2ServiceServer).SystemListMethods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Aria2Service_SystemListMethods_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Aria2ServiceServer).SystemListMethods(ctx, req.(*SystemListMethodsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Aria2Service_SystemListNotifications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SystemListNotificationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Aria2ServiceServer).SystemListNotifications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Aria2Service_SystemListNotifications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Aria2ServiceServer).SystemListNotifications(ctx, req.(*SystemListNotificationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Aria2Service_ServiceDesc is the grpc.ServiceDesc for Aria2Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Aria2Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aria2go.api.Aria2Service",
	HandlerType: (*Aria2ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddUri",
			Handler:    _Aria2Service_AddUri_Handler,
		},
		{
			MethodName: "AddTorrent",
			Handler:    _Aria2Service_AddTorrent_Handler,
		},
		{
			MethodName: "AddMetalink",
			Handler:    _Aria2Service_AddMetalink_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _Aria2Service_Remove_Handler,
		},
		{
			MethodName: "ForceRemove",
			Handler:    _Aria2Service_ForceRemove_Handler,
		},
		{
			MethodName: "Pause",
			Handler:    _Aria2Service_Pause_Handler,
		},
		{
			MethodName: "PauseAll",
			Handler:    _Aria2Service_PauseAll_Handler,
		},
		{
			MethodName: "ForcePause",
			Handler:    _Aria2Service_ForcePause_Handler,
		},
		{
			MethodName: "ForcePauseAll",
			Handler:    _Aria2Service_ForcePauseAll_Handler,
		},
		{
			MethodName: "Unpause",
			Handler:    _Aria2Service_Unpause_Handler,
		},
		{
			MethodName: "UnpauseAll",
			Handler:    _Aria2Service_UnpauseAll_Handler,
		},
		{
			MethodName: "TellStatus",
			Handler:    _Aria2Service_TellStatus_Handler,
		},
		{
			MethodName: "TellActive",
			Handler:    _Aria2Service_TellActive_Handler,
		},
		{
			MethodName: "TellWaiting",
			Handler:    _Aria2Service_TellWaiting_Handler,
		},
		{
			MethodName: "TellStopped",
			Handler:    _Aria2Service_TellStopped_Handler,
		},
		{
			MethodName: "GetUris",
			Handler:    _Aria2Service_GetUris_Handler,
		},
		{
			MethodName: "GetFiles",
			Handler:    _Aria2Service_GetFiles_Handler,
		},
		{
			MethodName: "GetPeers",
			Handler:    _Aria2Service_GetPeers_Handler,
		},
		{
			MethodName: "GetServers",
			Handler:    _Aria2Service_GetServers_Handler,
		},
		{
			MethodName: "GetGlobalStat",
			Handler:    _Aria2Service_GetGlobalStat_Handler,
		},
		{
			MethodName: "GetOption",
			Handler:    _Aria2Service_GetOption_Handler,
		},
		{
			MethodName: "ChangeOption",
			Handler:    _Aria2Service_ChangeOption_Handler,
		},
		{
			MethodName: "GetGlobalOption",
			Handler:    _Aria2Service_GetGlobalOption_Handler,
		},
		{
			MethodName: "ChangeGlobalOption",
			Handler:    _Aria2Service_ChangeGlobalOption_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _Aria2Service_Shutdown_Handler,
		},
		{
			MethodName: "ForceShutdown",
			Handler:    _Aria2Service_ForceShutdown_Handler,
		},
		{
			MethodName: "SaveSession",
			Handler:    _Aria2Service_SaveSession_Handler,
		},
		{
			MethodName: "SystemMulticall",
			Handler:    _Aria2Service_SystemMulticall_Handler,
		},
		{
			MethodName: "SystemListMethods",
			Handler:    _Aria2Service_SystemListMethods_Handler,
		},
		{
			MethodName: "SystemListNotifications",
			Handler:    _Aria2Service_SystemListNotifications_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aria2.proto",
}
